apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duckietv
  namespace: duckietv
  annotations:
    cert-manager.io/cluster-issuer: step-ca-acme-external
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Keeping it simple to fix the 404
spec:
  ingressClassName: traefik
  rules:
    - host: duckie.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: duckietv
                port:
                  number: 3000
  tls:
    - hosts:
        - duckie.homelab.local
      secretName: duckietv-tls
