---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-mongodb-init
  namespace: unifi
  labels:
    app: unifi-mongodb
data:
  init-mongo.js: |
    db.getSiblingDB("unifi").createUser({
      user: "unifi",
      pwd: "unifi-mongo-password-change-me",
      roles: [
        { role: "dbOwner", db: "unifi" },
        { role: "dbOwner", db: "unifi_stat" }
      ]
    });
