---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-web
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.104
  ports:
  - name: web-ui
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: guest-https
    port: 8843
    targetPort: 8843
    protocol: TCP
  - name: guest-http
    port: 8880
    targetPort: 8880
    protocol: TCP
  selector:
    app: unifi-controller
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-comm
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.104
  ports:
  - name: device-comm
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: stun
    port: 3478
    targetPort: 3478
    protocol: UDP
  - name: discovery
    port: 10001
    targetPort: 10001
    protocol: UDP
  - name: speedtest
    port: 6789
    targetPort: 6789
    protocol: TCP
  selector:
    app: unifi-controller
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-mongodb
  namespace: unifi
  labels:
    app: unifi-mongodb
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: unifi-mongodb
