---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.100
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: unifi-skip-verify@kubernetescrd
spec:
  type: LoadBalancer
  ports:
  - name: device-comm
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: web-ui
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: stun
    port: 3478
    targetPort: 3478
    protocol: UDP
  - name: discovery
    port: 10001
    targetPort: 10001
    protocol: UDP
  - name: speedtest
    port: 6789
    targetPort: 6789
    protocol: TCP
  - name: syslog
    port: 5514
    targetPort: 5514
    protocol: UDP
  - name: https-redirect
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: unifi-controller
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-db
  namespace: unifi
  labels:
    app: unifi-db
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: unifi-db
